"""add_benefits_columns_to_registrations_and_reviews

Revision ID: 0c68d1998838
Revises: be83c1967485
Create Date: 2025-10-26 18:53:12.533448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c68d1998838'
down_revision = 'be83c1967485'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_worker_id', sa.Integer(), nullable=False, comment='ID of the social worker (user) who submitted the review'),
    sa.Column('student_registration_id', sa.Integer(), nullable=False, comment='ID of the student registration being reviewed (one-to-one)'),
    sa.Column('review', sa.JSON(), nullable=False, comment='JSON payload containing the review form data'),
    sa.Column('ivs', sa.Numeric(precision=10, scale=2), nullable=False, comment='Calculated Vulnerability Score (IVS)'),
    sa.Column('approved_food_allowance', sa.Boolean(), nullable=True, comment='Whether food allowance benefit was approved (null if not applicable)'),
    sa.Column('approved_housing_allowance', sa.Boolean(), nullable=True, comment='Whether housing allowance benefit was approved (null if not applicable)'),
    sa.Column('approved_daycare_allowance', sa.Boolean(), nullable=True, comment='Whether daycare allowance benefit was approved (null if not applicable)'),
    sa.Column('approved_graduation_scholarship', sa.Boolean(), nullable=True, comment='Whether graduation scholarship benefit was approved (null if not applicable)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['social_worker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_registration_id'], ['student_registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_registration_id')
    )
    op.create_index(op.f('ix_review_registrations_id'), 'review_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_review_registrations_social_worker_id'), 'review_registrations', ['social_worker_id'], unique=False)
    op.drop_index(op.f('ix_student_documents_id'), table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_column('notice_teams', 'role')
    op.drop_column('notices', 'year')
    op.add_column('student_registrations', sa.Column('requested_food_allowance', sa.Boolean(), nullable=False, comment='Indicates if the student requested food allowance benefit'))
    op.add_column('student_registrations', sa.Column('requested_housing_allowance', sa.Boolean(), nullable=False, comment='Indicates if the student requested housing allowance benefit'))
    op.add_column('student_registrations', sa.Column('requested_daycare_allowance', sa.Boolean(), nullable=False, comment='Indicates if the student requested daycare allowance benefit'))
    op.add_column('student_registrations', sa.Column('requested_graduation_scholarship', sa.Boolean(), nullable=False, comment='Indicates if the student requested graduation scholarship benefit'))
    op.alter_column('student_registrations', 'answer',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="JSON data containing the student's answers to the notice questions",
               existing_comment='answer está aqui!!!',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_registrations', 'answer',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='answer está aqui!!!',
               existing_comment="JSON data containing the student's answers to the notice questions",
               existing_nullable=True)
    op.drop_column('student_registrations', 'requested_graduation_scholarship')
    op.drop_column('student_registrations', 'requested_daycare_allowance')
    op.drop_column('student_registrations', 'requested_housing_allowance')
    op.drop_column('student_registrations', 'requested_food_allowance')
    op.add_column('notices', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False, comment='Ano de vigência'))
    op.add_column('notice_teams', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='COORDINATOR ou SOCIAL_WORKER'))
    op.create_table('student_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_registration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nome original do arquivo'),
    sa.Column('file_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False, comment='Chave do arquivo no storage'),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='MIME type do arquivo'),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True, comment='Tamanho do arquivo em bytes'),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Descrição adicional do documento'),
    sa.ForeignKeyConstraint(['student_registration_id'], ['student_registrations.id'], name=op.f('student_documents_student_registration_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_documents_pkey'))
    )
    op.create_index(op.f('ix_student_documents_id'), 'student_documents', ['id'], unique=False)
    op.drop_index(op.f('ix_review_registrations_social_worker_id'), table_name='review_registrations')
    op.drop_index(op.f('ix_review_registrations_id'), table_name='review_registrations')
    op.drop_table('review_registrations')
    # ### end Alembic commands ###
