"""Initial migration with all models including audit_logs

Revision ID: 10f7d8796c33
Revises: 
Create Date: 2025-11-11 00:30:25.293393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f7d8796c33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome descritivo do periodo'),
    sa.Column('init_date', sa.DateTime(timezone=True), nullable=False, comment='Data de início do período'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False, comment='Data de fim do período'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periods_id'), 'periods', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periods_id'), table_name='periods')
    op.drop_table('periods')
    # ### end Alembic commands ###
