"""remove_document_type_and_is_required_from_student_documents

Revision ID: 12ac49339dab
Revises: 48a9ff78a911
Create Date: 2025-10-24 08:25:52.204977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ac49339dab'
down_revision = '48a9ff78a911'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_documents', 'is_required')
    op.drop_column('student_documents', 'document_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_documents', sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Tipo do documento (identidade, comprovante_renda, etc.)'))
    op.add_column('student_documents', sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Se o documento é obrigatório'))
    # ### end Alembic commands ###
