"""add_student_registration_and_cpf_to_users

Revision ID: 157cf7c7d334
Revises: a9d5fd5702b2
Create Date: 2025-10-07 15:14:54.341176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157cf7c7d334'
down_revision = 'a9d5fd5702b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_registration', sa.String(length=20), nullable=True, comment='Número de matrícula do estudante (apenas para user_type=STUDENT)'))
    op.add_column('users', sa.Column('cpf', sa.String(length=14), nullable=True, comment='CPF do estudante (apenas para user_type=STUDENT)'))
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_index(op.f('ix_users_student_registration'), 'users', ['student_registration'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_student_registration'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_column('users', 'cpf')
    op.drop_column('users', 'student_registration')
    # ### end Alembic commands ###
