"""Add_User_Form_Draft

Revision ID: 17e942a2516f
Revises: cee220f2b4c3
Create Date: 2025-11-09 12:12:02.210171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e942a2516f'
down_revision = 'cee220f2b4c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_drafts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'form_drafts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_drafts', type_='foreignkey')
    op.drop_column('form_drafts', 'user_id')
    # ### end Alembic commands ###
