"""create user registration table

Revision ID: 2159c3dc0d5f
Revises: 2be886bea232
Create Date: 2025-10-21 16:09:01.298933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2159c3dc0d5f'
down_revision = '2be886bea232'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
