"""rm-constraint-nullable-col-IVS

Revision ID: 26ba00b57065
Revises: 441f0804fdd7
Create Date: 2025-10-30 10:29:10.527794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ba00b57065'
down_revision = '441f0804fdd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_registrations', 'ivs',
               existing_type=sa.NUMERIC(precision=200, scale=0),
               nullable=True,
               existing_comment='Calculated Vulnerability Score (IVS)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_registrations', 'ivs',
               existing_type=sa.NUMERIC(precision=200, scale=0),
               nullable=False,
               existing_comment='Calculated Vulnerability Score (IVS)')
    # ### end Alembic commands ###
