"""Make date fields nullable in notices

Revision ID: 290d2747e46f
Revises: 157cf7c7d334
Create Date: 2025-10-20 22:20:46.244071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '290d2747e46f'
down_revision = '157cf7c7d334'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notices', 'registration_start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Data de início das inscrições',
               existing_nullable=False)
    op.alter_column('notices', 'registration_end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_comment='Data de término das inscrições')
    op.alter_column('notices', 'appeal_start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Data de início da fase de recursos',
               existing_nullable=True)
    op.alter_column('notices', 'appeal_end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Data de término da fase de recursos',
               existing_nullable=True)
    op.alter_column('notices', 'preliminary_result_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Data de divulgação do resultado preliminar',
               existing_nullable=True)
    op.alter_column('notices', 'final_result_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Data de divulgação do resultado final',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notices', 'final_result_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Data de divulgação do resultado final',
               existing_nullable=True)
    op.alter_column('notices', 'preliminary_result_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Data de divulgação do resultado preliminar',
               existing_nullable=True)
    op.alter_column('notices', 'appeal_end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Data de término da fase de recursos',
               existing_nullable=True)
    op.alter_column('notices', 'appeal_start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Data de início da fase de recursos',
               existing_nullable=True)
    op.alter_column('notices', 'registration_end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Data de término das inscrições')
    op.alter_column('notices', 'registration_start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Data de início das inscrições',
               existing_nullable=False)
    # ### end Alembic commands ###
