"""rename_column_student_registration_to_registration_number

Revision ID: 2be886bea232
Revises: 290d2747e46f
Create Date: 2025-10-21 14:37:36.687233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be886bea232'
down_revision = '290d2747e46f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'notice_number')
    op.drop_column('notices', 'responsible_agency')
    op.add_column('student_registrations', sa.Column('answer', sa.JSON(), nullable=True, comment='answer está aqui!!!'))
    op.drop_column('student_registrations', 'notes')
    op.add_column('users', sa.Column('registration_number', sa.String(length=20), nullable=True, comment='Número de matrícula do estudante (apenas para user_type=STUDENT)'))
    op.drop_index(op.f('ix_users_student_registration'), table_name='users')
    op.create_index(op.f('ix_users_registration_number'), 'users', ['registration_number'], unique=True)
    op.drop_column('users', 'student_registration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_registration', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Número de matrícula do estudante (apenas para user_type=STUDENT)'))
    op.drop_index(op.f('ix_users_registration_number'), table_name='users')
    op.create_index(op.f('ix_users_student_registration'), 'users', ['student_registration'], unique=True)
    op.drop_column('users', 'registration_number')
    op.add_column('student_registrations', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('student_registrations', 'answer')
    op.add_column('notices', sa.Column('responsible_agency', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Órgão responsável'))
    op.add_column('notices', sa.Column('notice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Número do edital (ex: 05/2025)'))
    # ### end Alembic commands ###
