"""Add_FormDraft

Revision ID: 39aefd4e74bb
Revises: 8311009df401
Create Date: 2025-11-10 23:53:40.361530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39aefd4e74bb'
down_revision = '8311009df401'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('REVIEW', 'REGISTRATION', name='formsketchtype'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True, comment="JSON data containing the student's answers to the notice questions"),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_drafts_id'), 'form_drafts', ['id'], unique=False)
    op.add_column('appeals', sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of when the student fulfilled the appeal requirements.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appeals', 'fulfilled_at')
    op.drop_index(op.f('ix_form_drafts_id'), table_name='form_drafts')
    op.drop_table('form_drafts')
    # ### end Alembic commands ###
