"""add_student_documents_table

Revision ID: 48a9ff78a911
Revises: 2159c3dc0d5f
Create Date: 2025-10-24 08:02:15.609004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a9ff78a911'
down_revision = '2159c3dc0d5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_registration_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False, comment='Tipo do documento (identidade, comprovante_renda, etc.)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome original do arquivo'),
    sa.Column('file_key', sa.String(length=512), nullable=False, comment='Chave do arquivo no storage'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='MIME type do arquivo'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='Tamanho do arquivo em bytes'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='Se o documento é obrigatório'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descrição adicional do documento'),
    sa.ForeignKeyConstraint(['student_registration_id'], ['student_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_documents_id'), 'student_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_documents_id'), table_name='student_documents')
    op.drop_table('student_documents')
    # ### end Alembic commands ###
