"""remove_year_column

Revision ID: 5b0edb8d9d18
Revises: 02acccbeccbd
Create Date: 2025-10-21 15:06:04.740838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0edb8d9d18'
down_revision = '02acccbeccbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False, comment='Ano de vigência'))
    # ### end Alembic commands ###
