"""Rename benefit fields to English

Revision ID: 5fe97877fdb9
Revises: b84c73c41b28
Create Date: 2025-09-25 15:24:49.614378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe97877fdb9'
down_revision = 'b84c73c41b28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('food_allowance', sa.Boolean(), nullable=False, comment='Auxílio Alimentação'))
    op.add_column('notices', sa.Column('housing_allowance', sa.Boolean(), nullable=False, comment='Auxílio Moradia'))
    op.add_column('notices', sa.Column('daycare_allowance', sa.Boolean(), nullable=False, comment='Auxílio Creche'))
    op.add_column('notices', sa.Column('graduation_scholarship', sa.Boolean(), nullable=False, comment='Bolsa Pró-Graduando'))
    op.drop_column('notices', 'auxilio_alimentacao')
    op.drop_column('notices', 'bolsa_pro_graduando')
    op.drop_column('notices', 'auxilio_creche')
    op.drop_column('notices', 'auxilio_moradia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('auxilio_moradia', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notices', sa.Column('auxilio_creche', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notices', sa.Column('bolsa_pro_graduando', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notices', sa.Column('auxilio_alimentacao', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('notices', 'graduation_scholarship')
    op.drop_column('notices', 'daycare_allowance')
    op.drop_column('notices', 'housing_allowance')
    op.drop_column('notices', 'food_allowance')
    # ### end Alembic commands ###
