"""create_table_review_registration

Revision ID: 718125506e6b
Revises: 2159c3dc0d5f
Create Date: 2025-10-22 15:35:21.956547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '718125506e6b'
down_revision = '2159c3dc0d5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_worker_id', sa.Integer(), nullable=False, comment='ID of the social worker (user) who submitted the review'),
    sa.Column('student_registration_id', sa.Integer(), nullable=False, comment='ID of the student registration being reviewed (one-to-one)'),
    sa.Column('review', sa.JSON(), nullable=False, comment='JSON payload containing the review form data'),
    sa.Column('ivs', sa.Numeric(precision=10, scale=2), nullable=False, comment='Calculated Vulnerability Score (IVS)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['social_worker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_registration_id'], ['student_registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_registration_id')
    )
    op.create_index(op.f('ix_review_registrations_id'), 'review_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_review_registrations_social_worker_id'), 'review_registrations', ['social_worker_id'], unique=False)
    op.alter_column('student_registrations', 'answer',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="JSON data containing the student's answers to the notice questions",
               existing_comment='answer está aqui!!!',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_registrations', 'answer',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='answer está aqui!!!',
               existing_comment="JSON data containing the student's answers to the notice questions",
               existing_nullable=True)
    op.drop_index(op.f('ix_review_registrations_social_worker_id'), table_name='review_registrations')
    op.drop_index(op.f('ix_review_registrations_id'), table_name='review_registrations')
    op.drop_table('review_registrations')
    # ### end Alembic commands ###
