"""removendo status de student_refistration e colocando em review

Revision ID: 77f26eee6641
Revises: be83c1967485
Create Date: 2025-10-28 14:00:17.982106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77f26eee6641'
down_revision = 'be83c1967485'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_registrations', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'APPEAL', 'REVIEW', name='registrationstatus'), nullable=False))
    op.drop_column('student_registrations', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_registrations', sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'APPEAL', 'REVIEW', name='registrationstatus'), autoincrement=False, nullable=False))
    op.drop_column('review_registrations', 'status')
    # ### end Alembic commands ###
