"""criando a tabela appeal

Revision ID: 80a553241c2e
Revises: d84cbf216f39
Create Date: 2025-10-28 17:58:33.394741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a553241c2e'
down_revision = 'd84cbf216f39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_registration_id', sa.Integer(), nullable=False, comment='ID of the review registration being appealed (one-to-one)'),
    sa.Column('requested_documents', sa.JSON(), nullable=False, comment='JSON detailing requested documents and reasons for appeal'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_registration_id'], ['review_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appeals_id'), 'appeals', ['id'], unique=False)
    op.create_index(op.f('ix_appeals_review_registration_id'), 'appeals', ['review_registration_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appeals_review_registration_id'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_id'), table_name='appeals')
    op.drop_table('appeals')
    # ### end Alembic commands ###
