"""init

Revision ID: 8311009df401
Revises: 
Create Date: 2025-11-08 10:30:10.028152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8311009df401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('registration_start_date', sa.DateTime(timezone=True), nullable=False, comment='Data de início das inscrições'),
    sa.Column('registration_end_date', sa.DateTime(timezone=True), nullable=True, comment='Data de término das inscrições'),
    sa.Column('appeal_start_date', sa.DateTime(timezone=True), nullable=True, comment='Data de início da fase de recursos'),
    sa.Column('appeal_end_date', sa.DateTime(timezone=True), nullable=True, comment='Data de término da fase de recursos'),
    sa.Column('preliminary_result_date', sa.DateTime(timezone=True), nullable=True, comment='Data de divulgação do resultado preliminar'),
    sa.Column('final_result_date', sa.DateTime(timezone=True), nullable=True, comment='Data de divulgação do resultado final'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('food_allowance', sa.Boolean(), nullable=False, comment='Auxílio Alimentação'),
    sa.Column('housing_allowance', sa.Boolean(), nullable=False, comment='Auxílio Moradia'),
    sa.Column('daycare_allowance', sa.Boolean(), nullable=False, comment='Auxílio Creche'),
    sa.Column('graduation_scholarship', sa.Boolean(), nullable=False, comment='Bolsa Pró-Graduando'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_id'), 'notices', ['id'], unique=False)
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome descritivo do periodo'),
    sa.Column('init_date', sa.DateTime(timezone=True), nullable=False, comment='Data de início do período'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False, comment='Data de fim do período'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periods_id'), 'periods', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('NTI', 'STUDENT', 'COORDINATOR', 'SOCIAL_WORKER', name='usertype'), nullable=False, comment='Type of user: coordinator, student, social_worker, or nti'),
    sa.Column('registration_number', sa.String(length=20), nullable=True, comment='Número de matrícula do estudante (apenas para user_type=STUDENT)'),
    sa.Column('cpf', sa.String(length=14), nullable=True, comment='CPF do estudante (apenas para user_type=STUDENT)'),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_registration_number'), 'users', ['registration_number'], unique=True)
    op.create_table('notice_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome do documento'),
    sa.Column('file_key', sa.String(length=512), nullable=False, comment='Chave do arquivo no S3'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='Tipo do arquivo (PDF, DOC, etc.)'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='Tamanho do arquivo em bytes'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_documents_id'), 'notice_documents', ['id'], unique=False)
    op.create_table('notice_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_teams_id'), 'notice_teams', ['id'], unique=False)
    op.create_table('student_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True, comment="JSON data containing the student's answers to the notice questions"),
    sa.Column('requested_food_allowance', sa.Boolean(), nullable=False),
    sa.Column('requested_housing_allowance', sa.Boolean(), nullable=False),
    sa.Column('requested_daycare_allowance', sa.Boolean(), nullable=False),
    sa.Column('requested_graduation_scholarship', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_registrations_id'), 'student_registrations', ['id'], unique=False)
    op.create_table('review_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_worker_id', sa.Integer(), nullable=True, comment='ID of the social worker (user) who submitted the review'),
    sa.Column('student_registration_id', sa.Integer(), nullable=False, comment='ID of the student registration being reviewed (one-to-one)'),
    sa.Column('review', sa.JSON(), nullable=True, comment='JSON payload containing the review form data'),
    sa.Column('ocr_analisys', sa.JSON(), nullable=True, comment='JSON payload containing the review form data'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'APPEAL', 'REVIEW', name='registrationstatus'), nullable=False),
    sa.Column('ivs', sa.Numeric(precision=200, scale=0), nullable=True, comment='Calculated Vulnerability Score (IVS)'),
    sa.Column('approved_food_allowance', sa.Boolean(), nullable=False, comment='Whether food allowance benefit was approved (null if not applicable)'),
    sa.Column('approved_housing_allowance', sa.Boolean(), nullable=False, comment='Whether housing allowance benefit was approved (null if not applicable)'),
    sa.Column('approved_daycare_allowance', sa.Boolean(), nullable=False, comment='Whether daycare allowance benefit was approved (null if not applicable)'),
    sa.Column('approved_graduation_scholarship', sa.Boolean(), nullable=False, comment='Whether graduation scholarship benefit was approved (null if not applicable)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['social_worker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_registration_id'], ['student_registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_registration_id')
    )
    op.create_index(op.f('ix_review_registrations_id'), 'review_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_review_registrations_social_worker_id'), 'review_registrations', ['social_worker_id'], unique=False)
    op.create_table('student_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_registration_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome original do arquivo'),
    sa.Column('file_key', sa.String(length=512), nullable=False, comment='Chave do arquivo no storage'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='MIME type do arquivo'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='Tamanho do arquivo em bytes'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='Descrição adicional do documento'),
    sa.Column('ocr_status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='ocrstatus'), server_default='PENDING', nullable=False),
    sa.Column('ocr_results', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['student_registration_id'], ['student_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_documents_id'), 'student_documents', ['id'], unique=False)
    op.create_index(op.f('ix_student_documents_ocr_status'), 'student_documents', ['ocr_status'], unique=False)
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_registration_id', sa.Integer(), nullable=False, comment='ID of the review registration being appealed (one-to-one)'),
    sa.Column('requested_documents', sa.JSON(), nullable=False, comment='JSON detailing requested documents and reasons for appeal'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_registration_id'], ['review_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appeals_id'), 'appeals', ['id'], unique=False)
    op.create_index(op.f('ix_appeals_review_registration_id'), 'appeals', ['review_registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appeals_review_registration_id'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_id'), table_name='appeals')
    op.drop_table('appeals')
    op.drop_index(op.f('ix_student_documents_ocr_status'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_id'), table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_index(op.f('ix_review_registrations_social_worker_id'), table_name='review_registrations')
    op.drop_index(op.f('ix_review_registrations_id'), table_name='review_registrations')
    op.drop_table('review_registrations')
    op.drop_index(op.f('ix_student_registrations_id'), table_name='student_registrations')
    op.drop_table('student_registrations')
    op.drop_index(op.f('ix_notice_teams_id'), table_name='notice_teams')
    op.drop_table('notice_teams')
    op.drop_index(op.f('ix_notice_documents_id'), table_name='notice_documents')
    op.drop_table('notice_documents')
    op.drop_index(op.f('ix_users_registration_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_periods_id'), table_name='periods')
    op.drop_table('periods')
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_table('notices')
    # ### end Alembic commands ###
