"""remove_notice_number_&_responsible_agency

Revision ID: 9c9dcdc0ca6d
Revises: 5b0edb8d9d18
Create Date: 2025-10-21 17:30:55.383724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9dcdc0ca6d'
down_revision = '5b0edb8d9d18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'notice_number')
    op.drop_column('notices', 'responsible_agency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('responsible_agency', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Órgão responsável'))
    op.add_column('notices', sa.Column('notice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Número do edital (ex: 05/2025)'))
    # ### end Alembic commands ###
