"""removendo o valor unico do review_registration_id

Revision ID: ac91a0fcded4
Revises: b384c607972c
Create Date: 2025-10-29 10:45:35.192160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac91a0fcded4'
down_revision = 'b384c607972c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appeals_review_registration_id'), table_name='appeals')
    op.create_index(op.f('ix_appeals_review_registration_id'), 'appeals', ['review_registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appeals_review_registration_id'), table_name='appeals')
    op.create_index(op.f('ix_appeals_review_registration_id'), 'appeals', ['review_registration_id'], unique=True)
    # ### end Alembic commands ###
