"""Create notices table

Revision ID: b01b4b1086e1
Revises: e98f883b7b47
Create Date: 2025-09-19 15:18:43.789332

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b01b4b1086e1"
down_revision = "e98f883b7b47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("important_dates", sa.JSON(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("document_url", sa.String(length=512), nullable=True),
        sa.Column("coordinator_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coordinator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notices_id"), "notices", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notices")
    # ### end Alembic commands ###
