"""criando a tabela appeal

Revision ID: b384c607972c
Revises: 80a553241c2e
Create Date: 2025-10-28 18:00:12.007505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b384c607972c'
down_revision = '80a553241c2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
