"""Refactor notice model with new fields and relationships

Revision ID: b84c73c41b28
Revises: b01b4b1086e1
Create Date: 2025-09-22 11:55:18.807498

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b84c73c41b28"
down_revision = "b01b4b1086e1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notice_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notice_id", sa.Integer(), nullable=False),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Nome do documento"
        ),
        sa.Column(
            "file_url", sa.String(length=512), nullable=False, comment="URL do arquivo"
        ),
        sa.Column(
            "file_type",
            sa.String(length=50),
            nullable=True,
            comment="Tipo do arquivo (PDF, DOC, etc.)",
        ),
        sa.Column(
            "file_size",
            sa.Integer(),
            nullable=True,
            comment="Tamanho do arquivo em bytes",
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notice_documents_id"), "notice_documents", ["id"], unique=False
    )
    op.create_table(
        "notice_teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notice_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.String(length=50),
            nullable=False,
            comment="COORDINATOR ou SOCIAL_WORKER",
        ),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notice_teams_id"), "notice_teams", ["id"], unique=False)
    op.add_column(
        "notices",
        sa.Column(
            "notice_number",
            sa.String(length=50),
            nullable=False,
            comment="Número do edital (ex: 05/2025)",
        ),
    )
    op.add_column(
        "notices",
        sa.Column("year", sa.Integer(), nullable=False, comment="Ano de vigência"),
    )
    op.add_column(
        "notices",
        sa.Column(
            "responsible_agency",
            sa.String(length=255),
            nullable=False,
            comment="Órgão responsável",
        ),
    )
    op.add_column(
        "notices", sa.Column("auxilio_alimentacao", sa.Boolean(), nullable=False)
    )
    op.add_column("notices", sa.Column("auxilio_moradia", sa.Boolean(), nullable=False))
    op.add_column("notices", sa.Column("auxilio_creche", sa.Boolean(), nullable=False))
    op.add_column(
        "notices", sa.Column("bolsa_pro_graduando", sa.Boolean(), nullable=False)
    )
    op.alter_column(
        "notices",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "notices",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.drop_constraint(
        op.f("notices_coordinator_id_fkey"), "notices", type_="foreignkey"
    )
    op.drop_column("notices", "document_url")
    op.drop_column("notices", "important_dates")
    op.drop_column("notices", "coordinator_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notices",
        sa.Column("coordinator_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "notices",
        sa.Column(
            "important_dates",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "notices",
        sa.Column(
            "document_url", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("notices_coordinator_id_fkey"),
        "notices",
        "users",
        ["coordinator_id"],
        ["id"],
    )
    op.alter_column(
        "notices",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "notices",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_column("notices", "bolsa_pro_graduando")
    op.drop_column("notices", "auxilio_creche")
    op.drop_column("notices", "auxilio_moradia")
    op.drop_column("notices", "auxilio_alimentacao")
    op.drop_column("notices", "responsible_agency")
    op.drop_column("notices", "year")
    op.drop_column("notices", "notice_number")
    op.drop_index(op.f("ix_notice_teams_id"), table_name="notice_teams")
    op.drop_table("notice_teams")
    op.drop_index(op.f("ix_notice_documents_id"), table_name="notice_documents")
    op.drop_table("notice_documents")
    # ### end Alembic commands ###
