"""Initial migration with all models

Revision ID: bac283692401
Revises: 
Create Date: 2025-10-02 10:49:09.113693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac283692401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notice_number', sa.String(length=50), nullable=False, comment='Número do edital (ex: 05/2025)'),
    sa.Column('year', sa.Integer(), nullable=False, comment='Ano de vigência'),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('responsible_agency', sa.String(length=255), nullable=False, comment='Órgão responsável'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('food_allowance', sa.Boolean(), nullable=False, comment='Auxílio Alimentação'),
    sa.Column('housing_allowance', sa.Boolean(), nullable=False, comment='Auxílio Moradia'),
    sa.Column('daycare_allowance', sa.Boolean(), nullable=False, comment='Auxílio Creche'),
    sa.Column('graduation_scholarship', sa.Boolean(), nullable=False, comment='Bolsa Pró-Graduando'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_id'), 'notices', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('COORDINATOR', 'STUDENT', 'SOCIAL_WORKER', 'NTI', name='usertype'), nullable=False, comment='Type of user: coordinator, student, social_worker, or nti'),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('notice_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome do documento'),
    sa.Column('file_key', sa.String(length=512), nullable=False, comment='Chave do arquivo no S3'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='Tipo do arquivo (PDF, DOC, etc.)'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='Tamanho do arquivo em bytes'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_documents_id'), 'notice_documents', ['id'], unique=False)
    op.create_table('notice_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False, comment='COORDINATOR ou SOCIAL_WORKER'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_teams_id'), 'notice_teams', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notice_teams_id'), table_name='notice_teams')
    op.drop_table('notice_teams')
    op.drop_index(op.f('ix_notice_documents_id'), table_name='notice_documents')
    op.drop_table('notice_documents')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_table('notices')
    # ### end Alembic commands ###
