"""Add_Form_Draft

Revision ID: cee220f2b4c3
Revises: 24fc02ee6229
Create Date: 2025-11-09 12:09:32.431491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee220f2b4c3'
down_revision = '24fc02ee6229'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('REVIEW', 'REGISTRATION', name='formsketchtype'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True, comment="JSON data containing the student's answers to the notice questions"),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_drafts_id'), 'form_drafts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_drafts_id'), table_name='form_drafts')
    op.drop_table('form_drafts')
    # ### end Alembic commands ###
