"""adicionando a colunm ocr_analisys

Revision ID: d84cbf216f39
Revises: e099fe7b2420
Create Date: 2025-10-28 16:13:39.362144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd84cbf216f39'
down_revision = 'e099fe7b2420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_registrations', 'ivs',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=200, scale=0),
               existing_comment='Calculated Vulnerability Score (IVS)',
               existing_nullable=False)
    op.drop_column('student_registrations', 'registration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_registrations', sa.Column('registration_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('review_registrations', 'ivs',
               existing_type=sa.Numeric(precision=200, scale=0),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_comment='Calculated Vulnerability Score (IVS)',
               existing_nullable=False)
    # ### end Alembic commands ###
