"""adicionando a colunm ocr_analisys

Revision ID: e099fe7b2420
Revises: 77f26eee6641
Create Date: 2025-10-28 14:05:35.528537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e099fe7b2420'
down_revision = '77f26eee6641'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_registrations', sa.Column('ocr_analisys', sa.JSON(), nullable=False, comment='JSON payload containing the review form data'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_registrations', 'ocr_analisys')
    # ### end Alembic commands ###
