"""Add user_type enum field

Revision ID: e98f883b7b47
Revises: b3b96228503c
Create Date: 2025-09-19 14:13:13.977816

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e98f883b7b47"
down_revision = "b3b96228503c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    usertype_enum = sa.Enum(
        "COORDINATOR", "STUDENT", "SOCIAL_WORKER", "NTI", name="usertype"
    )
    usertype_enum.create(op.get_bind())

    # Add the column with default value to handle existing rows
    op.add_column(
        "users",
        sa.Column(
            "user_type",
            usertype_enum,
            nullable=True,
            comment="Type of user: coordinator, student, social_worker, or nti",
        ),
    )

    # Update existing rows with a default value (STUDENT)
    op.execute("UPDATE users SET user_type = 'STUDENT' WHERE user_type IS NULL")

    # Now make it not nullable
    op.alter_column("users", "user_type", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_type")
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS usertype")
    # ### end Alembic commands ###
