"""Add_FullFilled_Col_Appeal

Revision ID: f34760c8fe20
Revises: 17e942a2516f
Create Date: 2025-11-10 14:32:17.968234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34760c8fe20'
down_revision = '17e942a2516f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeals', sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of when the student fulfilled the appeal requirements.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appeals', 'fulfilled_at')
    # ### end Alembic commands ###
